### ISSUE TITLE
Jess vs "{i,e,y,ica}" track columns

### ISSUE THREAD

**Issue by thejessleigh** [jessconf/jessconf.github.io#8]
It doesn't appear that people whose preferred names are Jess actually stay in the "Jess" column and there are several people in the "Jess" column with an "{i,e,y,ica}" variant. Should the tracks be eliminated? If not, we should separate by name as appropriate.

**Comment by jessfraz** [comment]
ya maybe we should just eliminate or one column might be way longer?

**Comment by thejessleigh** [comment]
I think the tracks are a cute idea, but I've seen names get shuffled around as new requests are merged in. It should either be consistent or ditched.

**Comment by jessfraz** [comment]
I removed them :)
